name: leaves1d
channels:
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - adios4dolfinx=0.9.5
  - fenics-dolfinx=0.9.0
  - ipykernel
  - matplotlib
  - mpich=4.3.2
  - numpy
  - pandas
  - pip
  - python=3.13
  - scipy
  - tqdm
  - pyvista==0.46.4
  - trame=3.12.0
  - ipywidgets
