name: leaves1d
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.13.*
  - numpy
  - scipy
  - matplotlib
  - pandas
  - tqdm
  - pyvista=0.46.3
  - trame=3.12.0
  - fenics-dolfinx=0.9.0
  - mpich=4.3.2
  - adios4dolfinx=0.9.5
  - ipykernel
  - pip  
  - pip:
      - gmsh==4.14.1